### ISSUE TITLE
p.98のclass Detect(Function)のエラー解決方法が分からない

### ISSUE THREAD

**Issue by masato-nakamura-tim** [YutaroOgawa/pytorch_advanced#102]
お世話になっております。
p.98のクラスDetect実装の部分で以下のエラーが発生し、調べてみたのですが、一向に解決できなさそうだったため、質問させていただきました。こちらどのようにすればエラー解決できますでしょうか？お手数おかけして申し訳ございませんがよろしくお願いいたします。

class Detect(Function):

  def __init__(self,conf_thresh=0.01,top_k=200,nms_thresh=0.45):
    self.softmax=nn.Softmax(dim=-1)
    self.conf_thresh=conf_thresh
    self.top_k=top_k
    self.nms_thresh=nms_thresh
  def forward(self,loc_data,conf_data,dbox_list):
    num_batch=loc_data.size(0)
    num_dbox=loc_data.size(1)
    num_classes=conf_data.size(2)
    conf_data=self.softmax(conf_data)
    output=torch.zeros(num_batch,num_classes,self,top_k,5)
    conf_preds=conf_data.transpose(2,1)
    for i in range(num_batch):
      decode_boxes=decode(loc_data[i],dbox_list)
      conf_scores=conf_preds[i],clone()
    for cl in range(1,num_classes):
      c_mask=conf_scores[cl].gt(self.conf_thresh)
      scores=conf_scores[cl][c_mask]
      if scores.nelement()==0:
        continue
      l_mask=c_mask.unsqueeze(1).expand_as(decode_boxes)
      boxes=decode_boxes[l_mask].voew(-1,4)
      ids,count=nm_suppression(
          boxes,scores,self.num_thresh,self.top_k
      )  
      output[i,cl,:count]=torch.cat((scores[ids[:count]]))

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
NameError                                 Traceback (most recent call last)
<ipython-input-47-4f21339312cc> in <module>()
----> 1 class Detect(Function):
      2 
      3   def __init__(self,conf_thresh=0.01,top_k=200,nms_thresh=0.45):
      4     self.softmax=nn.Softmax(dim=-1)
      5     self.conf_thresh=conf_thresh

NameError: name 'Function' is not defined

**Comment by masato-nakamura-tim** [comment]
こちら失礼いたしました。
https://github.com/YutaroOgawa/pytorch_advanced/issues/71とhttps://github.com/YutaroOgawa/pytorch_advanced/blob/236ef3ae2a8ff02cd6e69c7067c240e27e49356a/2_objectdetection/utils/ssd_model.py
に載っておりました。ありがとうございます。

**Comment by YutaroOgawa** [comment]
@masato-nakamura-tim さま

投稿ならびに、自己解決をありがとうございます。
既存のIssueならびに、（そもそも本書のアップデートが追いついていない）

ご指摘のとおり、PyTorch1.5以上からの問題

【第二章】2-8_SSD_inference.ipynb_推論時のエラーについて（PyTorchのバージョン1.5以上で発生）
https://github.com/YutaroOgawa/pytorch_advanced/issues/71

になります。

また、今後も気軽に、気になった点や、疑問点、困ったことを投稿してくださると、多くの読者の皆さまに役立つため、私も嬉しいです。

今後ともどうぞよろしくお願い致します。
