### ISSUE TITLE
【質問】【第４章：p.205】Datasetの動作確認について

### ISSUE THREAD

**Issue by EriHata** [YutaroOgawa/pytorch_advanced#119]
小川様
お世話になっております

p.205の1行目の
train_dataset = COCOkeypointsDataset(...
の引数に使われているのが、
val_img_list, val_mask_list, val_meta_list
なのですが、
train_img_list, train_mask_list, train_meta_list
のほうが正しいかと思って変更して実行すると以下のエラーが出ます。
OpenCV(4.2.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

調べると画像が読み込めていないときのエラーのようなのですが、何がいけないのかがわからないので教えていただけるとありがたいです。

**Comment by EriHata** [comment]
問題解決いたしました。
４章ではtrainデータは使用しないことをよく確認せずに、使用していると誤解したまま学習を進めてしまったことが原因でした。
拙い質問をしてしまい申し訳ありませんでした。

**Comment by YutaroOgawa** [comment]
@EriHata さま

まったく気になさらないでください。
自己解決されて、素晴らしいです！お疲れ様です！

**Comment by EriHata** [comment]
小川様

コメントありがとうございます、励みになります！
著書では解説と実装が丁寧に書かれており、多くのことを学ばさせて頂いて感謝しております。
今後とも宜しくお願いします。
