### ISSUE TITLE
5-4_SAGANのSelf-Attention Maps(o)への1x1 convolutionについて

### ISSUE THREAD

**Issue by takatea** [YutaroOgawa/pytorch_advanced#121]
こちらの参考書はとても分かりやすく知識だけでなく実装面でも非常に勉強になっております．
ありがとうございます．
今回こちらの本を輪講することとなり，そこで私が5章の担当をすることになりました．
その中で，実装を眺めていた所気になった点があったためご質問させていただきます．

**Self-Attention Generative Adversarial Networks**（SAGAN）の論文における``self-attention maps(o)``を計算する前には1x1 convolutionをしているのですが，小川さんの実装では1x1 convolutionが含まれていないようです．（SAGANの論文におけるFigure 2を見ていて気がつきました）
SAGANの論文上での3節を読んでみると，``convolution feature maps(x)``を一度すべて1x1 convolutionでチャンネル数を減らすため最後に元のチャンネル数へ戻すための1x1 convolution（v）を加えているようです．

ご質問としては，``5-4_SAGAN.ipynb``の実装ではSelf_Attentionクラスのコンストラクタ内，変数``self.value_conv``における1x1 convolutionは元の特徴マップのチャンネル数と同じにしているため，論文上における最後の1x1 convolutionを省いているのでしょうか？

一通り5章を読ませていただいたのですが，この点に関して明記されていないように思えたため質問させていただきました．
お手数をお掛けいたしますが，ご回答いただけると幸いです．
何卒よろしくお願いいたします．

**Comment by YutaroOgawa** [comment]
@takat0627 さま

こちらも、ご質問ありがとうございます。
本書の対応に使える時間を確保できず、大変申し訳ございません。

あまり意識せずに実装していたのですが、指摘されると確かに。
この理由はMNISTという簡易で小さな画像のためであると思います。
GitHubの該当節で参考にしているコードを見るのが良いかと思います。

適切な回答になっておらず、大変申し訳ございませんが、どうぞよろしくお願い致します。

**Comment by takat0627** [comment]
@YutaroOgawa 

お忙しい中ご回答ありがとうございます．

Githubのソースコードを参考に，実際に自分の対象に合わせたネットワークを組んでみたいと思います．
ありがとうございました．
