### ISSUE TITLE
【誤植】【p.373】位置情報テンソルの計算式

### ISSUE THREAD

**Issue by tealgreen0503** [YutaroOgawa/pytorch_advanced#15]
お世話になります．

【場所】
初版：p.373

【訂正】
位置情報テンソルの計算式が書籍の説明と書籍中のサンプルコードで異なっていました．原著論文や参考サイトを当たったところ，どうやらサンプルコードの方が正しいようです．

誤）

> PE(pos_word, 2i) = sin(pos_word / (1000^(2i/DIM)))
> PE(pos_word, 2i + 1) = cos(pos_word / (1000^(2i/DIM)))

正）

> PE(pos_word, 2i) = sin(pos_word / (10000^(2i/DIM)))
> PE(pos_word, 2i + 1) = cos(pos_word / (10000^(2i/DIM)))

ご確認いただければ幸いです．

**Comment by YutaroOgawa** [comment]
@tealgreen0503 さん

ありがとうございます。
誤植の情報と訂正情報までありがとうございます。
いただいた通りです。

次の版が発行される場合には、書面も訂正いたします。
ありがとうございます。
