### ISSUE TITLE
2-7_SSD_training.ipynbをcolaboratoryで行うには

### ISSUE THREAD

**Issue by NaokiToya** [YutaroOgawa/pytorch_advanced#163]
小川様

2_objectdetectionで 2-7_SSD_training.ipynb を実効しているところです。
AWSを使ったことがないので、先ずはcolaboratoryで試しています。
colab用にファイルパスは修正しました。
　Python: 3.7.10
　PyTorch: 1.2.0
　GPU選択(cuda0)

実行したところ、「# 学習・検証を実行する」のところで90分ルールで引っ掛かり
切断されてしまいます。
本にはAWSで6時間かかると書かれいます。
なので、90分ルールで引っ掛かって当然ですね。
colabで行うにはどのようにすればよいのでしょうか？

colaboratoryで試されている方ご教授頂ければ幸いです。
よろしくお願いします。

**Comment by YutaroOgawa** [comment]
@NaokiToya さま

ご質問ありがとうございます。
どなたかColaboraotryでのアドバイスがございましたら、お願いいたします。

（訓練中、定期的にネットワークを保存しておき、途中から再学習可能にするのも一つの手かと思います）
