### ISSUE TITLE
【第7章】7-5 訓練データとvalidationデータを分ける実装について

### ISSUE THREAD

**Issue by k-takeda-sgiken** [YutaroOgawa/pytorch_advanced#166]
torchtext.data.Datasetのsplit関数でデータを分ける処理で、エラーが出ています。

`train_ds, val_ds = train_val_ds.split(split_ratio=0.8, random_state=random.seed(1234))
`
ValueError:not enough values to unpach (expected 2, got 1)

PyTorchやtorchtextのバージョンを変えて試したのですが、修正できていないです。
原因をご存知でしたら教えていただきたいです。

**Comment by YutaroOgawa** [comment]
@k-takeda-sgiken さま

ご質問ありがとうございます。

torchtextは最近（数カ月前）にバージョンが上がって、大きく変更が入りました。

これまでのもの（本書の内容の一部）を使用する際にimport文を書き換える必要がある場合があります。

参考
https://plaza.rakuten.co.jp/taro3chidayo/diary/202103070000/

torchtext.legacy.datasets
をimportで使用することで解決するか試みていただけますでしょうか。

お手数をおかけしますがどうぞよろしくお願い致します

**Comment by k-takeda-sgiken** [comment]
早速の回答ありがとうございます。

> torchtext.legacy.datasets
> をimportで使用することで解決するか試みていただけますでしょうか。
→こちらもすでに試していてうまくいっていなかったのですが
　テキストのコードの模写で間違っていたことが判明いたしました。

お騒がせして申し訳ありませんでした。

**Comment by YutaroOgawa** [comment]
@k-takeda-sgiken さま

解決して良かったです！

ぜひまた気軽にご質問ください。今後ともどうぞよろしくお願い致します。
