### ISSUE TITLE
【質問】第2章　2-7　学習と研修の実施について、IndexError: too many indices for arrayが出ます

### ISSUE THREAD

**Issue by hiroto-oohashi** [YutaroOgawa/pytorch_advanced#177]
お世話になっております。
AWSを用い、自作のデータセットについて学習を行っていたところ、
イテレーションが40程度（何度やり直しても同じ程度）で表題のIndexError: too many indices for arrayが起きてしまいます。

デバッグを確認する限りでは
ssd_model.pyの259行目あたり
        # 3. 前処理を実施 
        img, boxes, labels = self.transform(img, self.phase, anno_list[:, :4], anno_list[:, 4])
この部分でエラーとなっています。

too many indices for arrayということは、配列に対しindicesが多すぎる...ということのように思うのですが、
１つも学習が進まないのならともかく、イテレーションがいくつか進むのが疑問です。

イテレーションの進め方としては、train.txtにある項目を、何分割かにして、そのうちの１つを学習しているのでしょうか。
拙い質問で申し訳ございません。
恐縮ではございますが、ご回答を検討いただけますと幸いです

**Comment by YutaroOgawa** [comment]
@hiroto-oohashi さま

ご質問いただき、誠にありがとうございます。

SSDモデルで自作のデータセットで訓練中と理解しました。

イテレーションの単位がデータセットまるまる全部で1回なのか、
ミニバッチごとに1回なのか、

2-7_SSD_training.ipynbの通りですと、データセットをまるまる1回で1 epoch、ミニバッチ1回で1 iterationとしています。
同じであると仮定します。


すると、40イテレーション目あたりで読み込んでいるデータのアノテーションかデータに不備、誤りがあるの可能性が考えられます。

まずは、イテレーションごとに読み込んでいるデータをチェックしてみて、エラーが毎回同じデータで発生しているのか、
もしくは、どのデータで発生しているのかを確かめるのが良いのではと思いました。

参考になれば、幸いです。どうぞよろしくお願いいたします。

**Comment by hiroto-oohashi** [comment]
@YutaroOgawa さま
ご返答いただきありがとうございます。
言葉不足の部分を補っていただきありがとうございます。
おかげ様で、アノテーションファイルの不備を発見いたしました。
現状問題は解決いたしました。

**Comment by hiroto-oohashi** [comment]
＠YutaroOgawaさま
エラーが引き続きでて困っております。
実行環境はVSCode上、
Python:3.8.10, PyTorch:1.9.0+cu102
CPUを使っております。

エラーは以下の通りです

[Errno 2] No such file or directory: './data/....（略）.../2061.xml'

エラーの発生場所はssd_model.pyの
        # xmlファイルを読み込む
        xml = ET.parse(xml_path).getroot()
この部分のエラーとなっているようです。

2061.xmlは確かに存在しないファイルなのですが、
この場合は
data>ImageSets>Main
のフォルダにあるtrain.txtから2061を削除すれば反映されるものでしょうか？

言い換えますと、トレーニングに使用するtrain.txtから、使わないデータを削除すれば、トレーニング時に使われなくなるものでしょうか？

大変初歩的な質問で恐れいります。
ご確認いただけますと幸いです。

**Comment by YutaroOgawa** [comment]
@hiroto-oohashi さま

解決の報告をありがとうございます。
一歩前に進めたようで、嬉しい限りです！

また、お困りの際は気軽にご質問くださいませ。
いろいろ知見が溜まり、本書の幅広い読者の方に有用になると思っています。

今後ともどうぞよろしくお願いいたします。

**Comment by hiroto-oohashi** [comment]
@YutaroOgawa さま
お世話になっております。

他エラーが出ており、再度質問させていただきたいと思います。
現在学習を、AWSとローカルPC上の２つで動かしているのですが、
ローカルPCでは問題なく20エポックほどまで学習できているのですが、
AWSでは

FileNotFoundError: [Errno 2] No such file or directory: './data/ano/Annotations/7422.xml'

と表示され、毎回同じエラーが出てしまいます。
このフォルダ内には
AW_7422.xml
のように、接頭辞がついたxmlファイルが存在しておりますが、
AW_の部分はコード内部の
    # 画像ファイルとアノテーションファイルへのパスのテンプレートを作成
の部分で書き換えております。（   annopath_template = osp.join(rootpath, 'Annotations','AW_%s.xml')　のように）

エラーのファイル名に「AW_」の接頭辞がついてないことから、ルートパスがうまく通っていないのか？
と仮説を立てておりますが、現状解決しておりません。
言葉足らずで大変恐縮ではございますが、何卒ご指摘等頂けますと幸いです

**Comment by hiroto-oohashi** [comment]
@YutaroOgawa さま
お騒がせしました。こちら自己解決しました。
utilsフォルダの中にある、ssd_model.pyのルートパスを書き換えていなかったことが原因のようでした。
大変失礼しました。

**Comment by YutaroOgawa** [comment]
@hiroto-oohashi さま

はい、承知しました。自己解決されたとのことで、とても良いことだと思います！
気になさらさず、引き続き、気軽にご質問くださいませ。

今後ともどうぞよろしくお願いします。
