### ISSUE TITLE
【第2章】ssd_model.pyのdef make_loc_conf()関数の引数について

### ISSUE THREAD

**Issue by NaokiToya** [YutaroOgawa/pytorch_advanced#178]
サンプルデータではなく、オリジナルデータで挑戦しています。
オリジナルデータでは、voc_classesは背景含め5個です。
ssd_model.pyのdef make_loc_conf()関数の引数である「num_classes」を21から5へ変更すべきでしょうか？
よろしくお願いします。

**Comment by YutaroOgawa** [comment]
@NaokiToya さま

質問、誠にありがとうございます。
自分のオリジナルでの試みをされていて素晴らしいですね。嬉しいです。

はい、def make_loc_conf()関数の引数 num_classesはご指摘の通り、5へ変更すべきです。

他にも変更するべき場所がある気がするのですが（具体的なラベル名を記述している部分など）、
正確に「こことこことここです」と答えられず、申し訳ございません。

（本書のプログラム、理解しやすさを優先し、拡張性、応用性を犠牲にしており。。。）

動作させてみて、エラー吐いたら、「ここ直さないと」と多少試行錯誤していただく必要があるかと思います。

どうぞよろしくお願いいたします。

**Comment by NaokiToya** [comment]
ogawa様

おかげさまでオリジナルデータでの検出はできました。
次のステップとして、
カメラで撮られた画像をリアルタイムで検出できないか検討中です。
ありがとうございました。

**Comment by YutaroOgawa** [comment]
@NaokiToya さま

報告を誠にありがとうございます。
本書を活用し、オリジナルにいろいろ試されておられて、著者冥利につきます！
また、いつでもご質問くださいませ。
誠にありがとうございます。
