### ISSUE TITLE
【質問】【第2章】2-8　推論に関して

### ISSUE THREAD

**Issue by hiroto-oohashi** [YutaroOgawa/pytorch_advanced#180]
いつも丁寧にご対応くださりありがとうございます。

おかげ様で、自作の推論モデルを作成することができました。
引き続き推論の部分なのですが、以下のエラーが出ており、うまくいかない状態です。

Error(s) in loading state_dict for SSD:
	size mismatch for conf.0.weight: copying a param with shape torch.Size([84, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([20, 512, 3, 3]).
	size mismatch for conf.0.bias: copying a param with shape torch.Size([84]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for conf.1.weight: copying a param with shape torch.Size([126, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([30, 1024, 3, 3]).
	size mismatch for conf.1.bias: copying a param with shape torch.Size([126]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for conf.2.weight: copying a param with shape torch.Size([126, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([30, 512, 3, 3]).
	size mismatch for conf.2.bias: copying a param with shape torch.Size([126]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for conf.3.weight: copying a param with shape torch.Size([126, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([30, 256, 3, 3]).
	size mismatch for conf.3.bias: copying a param with shape torch.Size([126]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for conf.4.weight: copying a param with shape torch.Size([84, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([20, 256, 3, 3]).
	size mismatch for conf.4.bias: copying a param with shape torch.Size([84]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for conf.5.weight: copying a param with shape torch.Size([84, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([20, 256, 3, 3]).
	size mismatch for conf.5.bias: copying a param with shape torch.Size([84]) from checkpoint, the shape in current model is torch.Size([20]).

読み込む推論モデルを、ssd300_mAP_77.43_v2に置き換えたりしてみたのですが、
同じエラーが表示される現状です。

いつもながら言葉足らずで大変申し訳ございません。
不足等ありましたらご指摘いただけますと幸いです。
よろしくお願い致します。

**Comment by YutaroOgawa** [comment]
@hiroto-oohashi さま

このエラーはおそらく、モデルを用意し、モデルにパラメータをロードしている箇所で発生していると判断しました。

```
net.load_state_dict(load_weights)
```
⇧のような感じの部分。


エラーとしては、保存されているモデルとしては[84, 512, 3, 3]のサイズを想定しているのに、
いまロードしようとしているモデルのサイズは[20, 512, 3, 3]になっています。。。
と言っているようです。

loadする前に、どこかでネットワークの形を変えた場所がないか？
が気になります。

もしくは訓練時の画像のサイズを変えていないか？
でしょうか。。。

どうぞよろしくお願いいたします。

小川雄太郎

**Comment by hiroto-oohashi** [comment]
すばやいご返答大変感謝いたしております。

情報不足で申し訳ありません。
おっしゃる通り、
net.load_state_dict(load_weights)
の部分でエラーが発生しております。

質問を重ねさせていただき恐縮なのですが、

①loadする前に、どこかでネットワークの形を変えた場所がないか？
ということは、モデルとしては問題ないが（ssd300_mAP_77.43_v2を使っているので、この場合は問題ないと考えられるが）、
その後の部分に異常があるという理解です。

ネットワークの形を変える、とは具体的にはどのようなことでしょうか？
以下の部分では、ネットワークの読み込みを行っているだけのように思います。コードのその他の部分で、ネットワーク変更に関わる部分がありますでしょうか。トレーニング前の設定でしょうか。

```
# SSDの学習済みの重みを設定
net_weights = torch.load('./weights/ssd300_mAP_77.43_v2.pth',
                         map_location={'cuda:0': 'cpu'})

net.load_state_dict(net_weights)
```
②もしくは訓練時の画像のサイズを変えていないか？
はトレーニング前の2-7に関するコードでよろしいでしょうか？

について、確認してみようと思います。

ご指摘ありがとうございます。

**Comment by YutaroOgawa** [comment]
@hiroto-oohashi さま


①
>ネットワークの形を変える、とは具体的にはどのようなことでしょうか？

net.load_state_dict()をしていますが、このnetという変数です。

このnetが

https://github.com/YutaroOgawa/pytorch_advanced/blob/master/2_objectdetection/2-8_SSD_inference.ipynb

では、

```
from utils.ssd_model import SSD
・・・
# SSDネットワークモデル
net = SSD(phase="inference", cfg=ssd_cfg)
```

として定義していますが、そうではないオリジナルな方法でnetを定義しているために、サイズが合わなくなっているのでは？
と思いました。

（もし書籍から何も変えていないとすれば、PyTorchのバージョンが悪さをしている可能性があります）


---

②
>②もしくは訓練時の画像のサイズを変えていないか？はトレーニング前の2-7に関するコードでよろしいでしょうか？

はい、2-7で入力しているオリジナルな画像のサイズが、書籍での画像のサイズと異なっていないか？
（異なっているためネットワークを変更していないか？）

が気になりました。


もし、書籍通りであり、ネットワークの形、入力画像の大きさ、を変えていないのであれば、PyTorchのバージョンが書籍よりも新しいために発生しているのかもしれません。

原因の探り方として、書籍通りの画像データや実装コードで実施してみてエラーが発生しないかを確認し、
書籍の時点ですでに現在のPyTorchのバージョンではうまくいかないのか。。。

それとも、オリジナルに変更しているところで何か問題が潜んでいるのか、を切り分けると良いかと思います。

どうぞよろしくお願いいたします。

**Comment by hiroto-oohashi** [comment]
@YutaroOgawa さま
ていねいなコメントありがとうございます。
・自分で修正したオリジナルの部分
・PyTorchのバージョン
などから、切り分けを行うということで承知しました。

ご指摘いただいた通り、書籍通りの部分と、オリジナル部分の差分を確認し、原因追及ができました。
原因はオリジナルの推論モデル構築ということで、クラス数を増やしていたこと、それに関してnum_classesを適切に変更できていなかったこと、関連したプログラムを十分に書き換えていなかったことのようでした。

いつも素早く、丁寧にご指導くださり大変ありがとうございます。
今度もとてもお世話になりました。
重ね重ねお礼申し上げます。

**Comment by YutaroOgawa** [comment]
@hiroto-oohashi さま

推論したいクラス数でしたか。

なるほど。私も勉強になります。
こちらこそ、誠にありがとうございます。
そして、迅速にいろいろと試して頂けて嬉しいです。
また是非気軽に、いろいろご質問ください。

本件も誠にありがとうございます。
