### ISSUE TITLE
【第7章】fastTextの学習済みモデルダウンロード

### ISSUE THREAD

**Issue by yuki1229ushioda** [YutaroOgawa/pytorch_advanced#189]

**Comment by yuki1229ushioda** [comment]
GDriveから「ファイルにアクセスする権限がありません」と表示され、ファイルを取得することができない現象が派生しました。
別のQiita記事からアクセスして見えるようになりましたが、そのご書籍のリンクからもアクセスできるようになりました。
一時的なアクセスエラーだったのかもしれません。
アクセスエラー時に起票していしましましたが(しかも操作ミスで途中でIssueをOpenしていしましました)そのご問題なくアクセスできたのでIssueはクローズさせていただきます。
お騒がせしてすみません。

**Comment by YutaroOgawa** [comment]
@yuki1229ushioda さま

ありがとうございます。

Qiita記事を執筆して下さっていた方が一時的にGoogle Dirveを設定を変更していて、
アクセス権限が許可制になったが、
誰でもアクセスできるように設定を戻されたのかもしれません。

ひとまず解決したとのことで、良かったです。

ご報告いただき、誠にありがとうございます！
