### ISSUE TITLE
【第4章】4.1 P.191 OpenPose PAFsのリンクの数は37本ではなく、19本？　 question

### ISSUE THREAD

**Issue by taikoma** [YutaroOgawa/pytorch_advanced#39]
PAFsのリンクの数が37本とありますが、19本の間違いじゃないでしょうか。

PAFsには、2点を結ぶベクトルの単位ベクトルが格納されるかと思います。
各リンク、単位ベクトルx方向と、単位ベクトルy方向を作成するので、１つのリンクにつき、２つのチャネルが割り当てられます。なので、チャンネル数は合計38(19×2)になるかと思います。P.186にリンクの図がありますが、この図に加えて、「右耳-右肩」、「左耳-左肩」の２本を加えて合計19本のリンク数になるかなと。

アノテーション作成のソースコードdataloader.pyのget_ground_truth関数を確認しましたが、pafsの配列（mid_1とmid_2）の作成では19個のリンクを作成しているようにみえます。
また、putVecMaps関数で、各リンクで、単位ベクトルのx方向とy方向と２つの配列を作成しているようにみえました。

こちらの勘違いでしたら申し訳ありませんが、確認したく質問させていただきました。

**Comment by YutaroOgawa** [comment]
@taikoma さま

返信が遅くなり、申し訳ございません。
見返しましたが完全に@takikomaさまが上記でご指摘されている通りです。

19本のPAFsについて、x軸方向、,y軸方向で各ピクセルがリンクである確率度合いをヒートマップ化しているため、その結果38チャネルが出力されます。

リンク数も図4.1.2で表記したものに加えて、おっしゃる通り、「右耳-右肩」、「左耳-左肩」の２本を足して、19本でした。

勘違いをしたまま記載していたので、次の改訂時には、いただいた内容を書面の修正に反映させていただきます。

またIssueで訂正を挙げます。

非常に重要なご指摘をいただき、誠にありがとうございました。

**Comment by taikoma** [comment]
> @taikoma さま
> 
> 返信が遅くなり、申し訳ございません。
> 見返しましたが完全に@takikomaさまが上記でご指摘されている通りです。
> 
> 19本のPAFsについて、x軸方向、,y軸方向で各ピクセルがリンクである確率度合いをヒートマップ化しているため、その結果38チャネルが出力されます。
> 
> リンク数も図4.1.2で表記したものに加えて、おっしゃる通り、「右耳-右肩」、「左耳-左肩」の２本を足して、19本でした。
> 
> 勘違いをしたまま記載していたので、次の改訂時には、いただいた内容を書面の修正に反映させていただきます。
> 
> またIssueで訂正を挙げます。
> 
> 非常に重要なご指摘をいただき、誠にありがとうございました。

**Comment by taikoma** [comment]
お忙しい中、ご確認とご返信ありがとうございます。
こちらの本ですが、丁寧な解説と充実したソースコードに大変助けられております。
