### ISSUE TITLE
【第1章」P.20、trainでオーギュメンテーション非実施のResize設置とtestのcrop必要性

### ISSUE THREAD

**Issue by umesaku** [YutaroOgawa/pytorch_advanced#51]
※pytorch_tutorialで理解しました。回答不要です。削除方法がわからず追記しました。申し訳ございません。

kerasからpytorchへ移行中の初心者です。

* 質問パート：第1章、P20、calss_ImageTransform（）
* 質問箇所：def __init__(self, resize, mean, sed):
　self.data_transform={・・・

* 質問1：
　'train': でオーギュメンテーション非実施の場合は
　'test'：と同じく、Composeでまず**transforms.Resize**から始めようと考えていますが、
　問題ないでしょうか？

* 質問2：
　'test'：同様に、'train'でオーギュメンテーション非実施の場合、cropも不要と思いますが、
　問題ございませんでしょうか？

お手すきの際、ご回答をお願いします。

**Comment by YutaroOgawa** [comment]
@umesaku さま

ご連絡ありがとうございます。
ご理解完了とのことで承知しました。

本書にて学習をいただき、誠にありがとうございます。
また、ご不明点などございましたら、気軽にご連絡くださいません。

Issueを閉じることで、非表示状態にいたします。


小川雄太郎

**Comment by YutaroOgawa** [comment]
解決済みのため、Issueを閉じます。
