### ISSUE TITLE
第4刷_第1章_P.29、P53　epoch_acc分子の正解数をdoubleにする理由

### ISSUE THREAD

**Issue by umesaku** [YutaroOgawa/pytorch_advanced#53]
・accuracy計算：
　分子の正解数epoch_correctsをdoubleにしておられる理由を教えてください。
 　チュートリアルもdoubleでした。
　下記、doubleしないほうが良いと考えています。

　```epoch_acc = running_corrects / dataset_sizes[phase]```

**Comment by YutaroOgawa** [comment]
@umesaku さま

ご質問ありがとうございます。

本書のdouble部分は、PyTorchの公式チュートリアルに合わせて、doubleにしています。

（umesakaさんはご理解されていると思われますが）
running_corrects、dataset_sizes[phase]の両者はintなので、
int同士の割り算はintになるため、doubleやfloatに型変換する必要があります。

umesakaさんのご質問は、なぜfloatではなくdoubleなのか？
という意図と解釈しました。

ここをfloatではなく、doubleにした理由は私にはありません
（チュートリアルに合わせたというのが理由です）

PyTorchはほとんど他の部分もfloat型にしているので、そこに合わせておく方が、
どこかで型不一致の計算エラーが生まれるのを回避できるため、
私は、doubleにせず、floatの方が良いとは思います。

ただ、本書の序盤なので、公式チュートリアルに合わせています、
というのが回答となります。

どうぞよろしくお願い致します。

**Comment by umesaku** [comment]
ご回答ありがとうございます。

doubleにした理由、doubleにせずfloatの方が良いとお考えの件、
あわせて丁寧なご説明、感謝します。
公式チュートリアルとはいえ有志の方々で作成しているようで可読性の低いコードが散見されます。

cocloseいただいて構いません。

ありがとうございました。

**Comment by YutaroOgawa** [comment]
@umesaku さん

はい、ありがとうございます。
それでは、closeいたします。
今後ともどうぞ宜しくお願い致します。
