### ISSUE TITLE
【第２章】学習のlossグラフについて

### ISSUE THREAD

**Issue by xmba15** [YutaroOgawa/pytorch_advanced#55]
始めまして。
本書の第２章では物体検出の学習の合計loss(loss_c+loss_l)グラフが乗っていると思いますが,loss_cとloss_l別のグラフも参考にしたいので、できれば,loss別のグラフを載せていただきますか？

**Comment by YutaroOgawa** [comment]
@xmba15 さま

ありがとうございます。
改訂する機会がありましたら、いただいた内容検討させてください。
貴重なご意見ありがとうございます。

現状で確認するには、現在の合計loss(loss_c+loss_l)と同じように、loss_cとloss_lを一度リストに格納して、csvで出力するのが良いかと思います。

どうぞよろしくお願い致します。
