### ISSUE TITLE
【第5章】p268 Self-Attentionの説明についての質問

### ISSUE THREAD

**Issue by yaneura-no-gomi** [YutaroOgawa/pytorch_advanced#56]
第5章 p268におけるSelf-Attentionの説明で少し分からなかった箇所があったので、質問させてください

Self-Attention Mapを作成する際に、sizeが<img src="https://latex.codecogs.com/gif.latex?$C&space;\times&space;N$" />の<img src="https://latex.codecogs.com/png.latex?$x$" />から<img src="https://latex.codecogs.com/png.latex?$S&space;=&space;$x$^Tx$" />を計算すると、「その要素<img src="https://latex.codecogs.com/png.latex?$s_{i,j}$" />は画像位置iと画像位置jがどれくらい似ているかを示す」と書かれていました

正規化されているベクトルの内積であれば<img src="https://latex.codecogs.com/png.latex?$s_{i,j}$" />がcos類似度に一致するため、腑に落ちるのですが、正規化されていない場合でも同じことが言えるのか？と気になりました
確かに本文中で「類似度」という厳密な言葉は使われていないことから、端的に説明するためにこういう書き方をされているのかなとも考えたのですが、確認のため質問させていただきました

お忙しいところ大変恐縮ですが、回答よろしくお願いいたします

**Comment by YutaroOgawa** [comment]
@yaneura-no-gomi さま

ご連絡、ご質問をありがとうございます。
非常に丁寧に本書を活用いただけていてとても嬉しいです。

@yaneura-no-gomi さまのおっしゃる通り、正規化されていればcos類似度と同じ計算と捉えられます。

では、ベクトルxは正規化されていないかのか？
、と言いますと、大雑把な意味では、正規化が事前に実施されています。

というのもベクトルxは画像の全ピクセルをチャネルごとに並べたものです。
ディープラーニングで画像を入力する際には、
第2章などでも実施しているように前処理で正規化して扱います
（第5章では正規化は入れていないのですが）。

つまり訓練データセットの画像、RGBの各チャネルについて、全画像について、平均0、標準偏差1の統計的特徴になるように変換しています。

また仮に正規化をしていなかったとしても、画像なのでピクセル間の関係、すなわちベクトルxのとある要素と、別のとある要素、というのはまったくの無関係で独立なものではありません
（同じ画像内のピクセルなので）

そうした前提があるため、正規化項が入っていなくてもベクトル同士の演算
S=x^T*xがcos類似度のように、類似度的なものになります。

@yaneura-no-gomi さまのおっしゃる通り、厳密な類似度ではないので、類似度的なものです。
本書文面の意図は上記の通りとなります。
書面、言葉足らずで申し訳ございません。

どうぞ宜しくお願い致します。

**Comment by yaneura-no-gomi** [comment]
回答ありがとうございます！
理解が深まったと思います
今後もなにかつまづいてしまったら質問させていただきたいと思うので、その際は何卒よろしくお願いします
