### ISSUE TITLE
【第8章】p.432 BERTのためのデータ読み込みについて

### ISSUE THREAD

**Issue by yaneura-no-gomi** [YutaroOgawa/pytorch_advanced#59]
第8章p432の記述について質問です
DataLoaderによって各文章が[PAD]の追加によって256単語に統一されて取り出され、さらにBERTに入力される際にまた[PAD]が追加されて512単語として扱われるということが書かれていました
しかし、具体的にどこの処理で[PAD]が追加され、256から512にされているのかが分かりませんでした
ぜひ回答よろしくお願いします

**Comment by YutaroOgawa** [comment]
@yaneura-no-gomi さま

ご質問ありがとうございます。

書籍できちんと記述できておらず、申し訳ございません。

p.433の
max_length = 256
TEXT = torchtext.data.Field(・・・
で文章フィールド（256文字）を作成

torchtext.data.TabularDataset.splits(・・・
でデータセットを作成

torchtext.data.Iterator(・・・
でデータローダーを作成しています。

ここまで、256です。

そして、これがBERTに入ったとき、一番最初にEmbeddingsモジュール
に入ります。

p.406
        self.position_embeddings = nn.Embedding(
            config.max_position_embeddings, config.hidden_size)

ここで、config.max_position_embeddingsが512になっており、nn.Embeddingが足りない分をpaddingしてくれます。

https://pytorch.org/docs/stable/nn.html#embedding

図8.1.1の文章ID列が512で入っている絵になっていますが、ここは256ですね。
図が誤っており、大変申し訳ございません。

どうぞよろしくお願い致します。

**Comment by yaneura-no-gomi** [comment]
回答ありがとうございました！
理解できました
