### ISSUE TITLE
Posenetの　4-2_DataLoader (autosaved)　でimg = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)エラー

### ISSUE THREAD

**Issue by kato76** [YutaroOgawa/pytorch_advanced#63]
すみません。1か所　エラーが出て、直せません。原因わかりますでしょうか。
Posenetの　4-2_DataLoader (autosaved)で

In[6]# 画像
img = cv2.imread(val_img_list[index])
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)
plt.show()
を実行すると　下記のエラーが出ます。
error                                     Traceback (most recent call last)
<ipython-input-6-78bcf1c1f423> in <module>
      3 # 画像
      4 img = cv2.imread(val_img_list[index])
----> 5 img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
      6 plt.imshow(img)
      7 plt.show()

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

調べましたがわかりませんでした。

**Comment by YutaroOgawa** [comment]
@kato76 さま

ご連絡ありがとうございます。

私が、3日前にAWSで環境を作成したマシンで、ただいま
4_pose_estimationの
make_folders_and_data_downloads.ipynb
を実施し、
4-2_DataLoaderを回したところ、エラーなく、実行できました。


もしかしたら、 @kato76 さまの環境で、画像などのファイルの置き場所（ファイルパス）やファイルそのものが存在しない可能性があります。
（※ときおり、解凍エラーで画像が抜け落ちるなどもあり得ます・・・）

なお私が実行した際の、4章のフォルダ「data」は以下のようになっています。

どうぞよろしくお願い致します。

![4_data](https://user-images.githubusercontent.com/38151872/78418998-4393bf80-767c-11ea-941a-9efd895b3ff9.PNG)

**Comment by kato76** [comment]
ありがとうございます。AWSの環境でなく、まずは、自分のwinPCで行ってみているのですが、dataフォルダは同じになっていました。もう一回やりましたが、だめでした。AWS環境でないと駄目でしょうか。学習はAWSでやりますが、それ以外をまず、win10のPCで試そうとしています。

**Comment by YutaroOgawa** [comment]
@kato76 さま

ありがとうございます。
OpenCVは癖があり、Win10だと使いづらいですね。
OpenCV周りで苦戦する話はたまに聞きます。

最初にいただいた、エラーメッセージから推察するに、

https://teratail.com/questions/208538

https://ja.stackoverflow.com/questions/49260/python3-6-6%E3%81%AB%E3%81%A6cv2%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%97%E3%81%BE%E3%81%99

https://www.it-swarm.dev/ja/python/%E9%96%A2%E6%95%B0%E3%80%8Ccvtcolor%E3%80%8D%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%AEopencv%EF%BC%81srcempty%EF%BC%88%EF%BC%89/806847672/

あたりのサイトが参考になるかもしれません。

・Windowsなので、プログラムとパスがうまく一致していない可能性
・Windowsのkatoさんのフォルダパスの途中に変な文字が入っている可能性

などがあります。

一度、写真があるフォルダまでのパスを調べ、
そのパスがきちんと、コードで取得できているか（val_img_list[index]と一致しているか）
確認してみていただけますでしょうか？

**Comment by kato76** [comment]
ありがとうございます。できるようになりました。win10のPCのままやっています。dataフォルダ中身を消して、再度、ダウンロードしなおすなど、4_pose_estimationの
make_folders_and_data_downloads.ipynb
をすべて、やり直しましたら、エラーが出なくなりました。ありがとうございました。
特に、val2014.zipが、再度ダウンロードしたときは、6.489GBでしたが、エラーが出ていた時は、3.4GBでしたので、うまく、ダウンロードできていなかったようです。ダウンロードに何時間もかかるので、途中で、いじらないように、しないといけなかったのですね。ありがとうございました。できてよかったです。

**Comment by YutaroOgawa** [comment]
@kato76 さま

ありがとうございます。
良かったです。

今後も、不明点やお困りの際には気軽に投稿ください。
誠にありがとうございました。

**Comment by kato76** [comment]
小川様

　

　ありがとうございます。こういう本は、いつも挫折して、そのままに

なってしまうことが多いので。質問できて回答いただき、たすかりました。

また、よろしくお願いいたします。

**Comment by kato76** [comment]
小川様　

 

　すみません。別件ですが、SSDを転移学習させたいのですが、

おすすめの方法やXmlを作成するツールなど、ありますでしょうか。

**Comment by YutaroOgawa** [comment]
物体検出のアノテーションには、
MSのツールがおススメです。

Microsoft/VoTT: Visual Object Tagging Tool: An electron app for building end to end Object Detection Models from Images and Videos.

https://github.com/Microsoft/VoTT/


他にはこちらの記事が参考になります。

Annotationツール比較
https://qiita.com/shu-yusa/items/d19ea57e3cf9c4dbdce2

**Comment by kato76** [comment]
ありがとうございます。助かります。
