### ISSUE TITLE
4-2_DataLoader.ipynb 処理後（p.196, マスクデータの働きを確認）について

### ISSUE THREAD

**Issue by ryota328439** [YutaroOgawa/pytorch_advanced#66]
問い合わせの概要：
４章のDatasetを作成する際に，通常のRGB画像は読み込めるのですが，それに対応するマスクデータが存在せずエラーが出力されています．※記載のurl(dropbox)からダウンロードしたmask.tar.gzを解凍したフォルダを使用しています．

具体的に存在していない画像と現在の状態は以下です．

前提：４章「make_folders_and_downloads.ipynb」を実行後，p.193 図4.2.1のフォルダ構成になっていることを確認．

現在の状態：
p.194, 関数make_datapath_list(rootpath)実行後，p.196, 小項目.マスクデータの働きを確認 に記載のスクリプトを実行したところ，mask_COCO_val2014_000000000488.jpgが無いという旨のエラーが表示される．maskフォルダの中身を検索したところ該当する画像自体が存在していない．mask.tar.gzを再度ダウンロードしても該当する画像は存在していなかった．

想定される状況：
COCO.jsonに記載はあるがmask.tar.gzには含まれていないマスク画像がありエラーが発生している．mask_COCO_val2014_000000000488.jpg以外にも存在しない画像が複数枚ある．

気になる点があればご指摘いただけないでしょうか．
宜しくお願い申し上げます．

**Comment by YutaroOgawa** [comment]
@ryota328439 さま

ご連絡ありがとうございます。

私が2週間前に、AWSで作成した環境ではプログラムが動作し、
mask_COCO_val2014_000000000488.jpg
も存在していることを確認しました。

ファイルのダウンロードもしくは解凍時に、ファイルが消えてしまったと思われます。
※ファイルはそこまで大きくないのですが、ファイル数が多い圧縮ファイルです。

第2章、第4章など、大きなファイルのダウンロードと解凍で、このようなファイルが不足する・消える現象が、他の読者からも報告されています。

以下参考
https://github.com/YutaroOgawa/pytorch_advanced/issues/63

ファイルのダウンロード方法や解凍方法、実行環境（ローカルであれば、AWSで試す）などを変えてみるなどをお願い致します。

**Comment by ryota328439** [comment]
小川様

下記理由でした．
> ファイルのダウンロードもしくは解凍時に、ファイルが消えてしまったと思われます。
> ※ファイルはそこまで大きくないのですが、ファイル数が多い圧縮ファイルです。

解凍方法と解凍先を変更することで消えていたファイルを確認しました．

迅速なご対応誠にありがとうございます．
参考書の内容も分かりやすく非常に助かっています．
引き続き勉強させていただきます．

**Comment by YutaroOgawa** [comment]
@ryota328439 さま

早速のご対応ありがとうございます。
他の読者の方も同じ状況に直面する可能性があるので、非常に助かります。

この度はありがとうございました。
今後ともどうぞ宜しくお願い致します。
