### ISSUE TITLE
【質問】3章　PSPNet　小GPUメモリで精度を得るには？

### ISSUE THREAD

**Issue by otsuka0212** [YutaroOgawa/pytorch_advanced#70]
※過去のIssuesに見つかりませんでしたので、投稿します。類似の投稿がありましたら、紹介をお願いいたします。

GPUメモリが5GBのノートPCで、
3章のPSPNetを動作させようとしています。

そこで、以下のようにハイパーパラメータを変更し、動作するようになりました。
input_size 475->256
img_size_8（PyramidPooling）　60->32
転移学習からスクラッチに変更。
batch_size 8->3
base_lr 1e-3->1e-4

その結果、メモリエラーを回避し、
train_loss 10epochで0.5程度に収束、val_loss 20epochで0.55に収束するのですが、
推定結果画像には全面黒で、推定できていません。

折角、メモリエラーを回避できるようになったので、
何らか結果が得られるようにしたいのですが、
何か手頃な方法はありませんでしょうか。

例えば、オリジナルは、150クラスを21クラスに縮小していますので、
私の方では更にクラス数を減らしても構いません。
ただ、その場合に、
data\VOCdevkit\VOC2012\ImageSets\Segmentation\train.txt
のままでよいのか、間引いた方がよいのか、
間引くとしたら、どう間引いたらよいのか、
分かりません。

クラス数以外でも構いません。

よろしくお願いします。

**Comment by YutaroOgawa** [comment]
@otsuka0212 さま

ご質問ありがとうございます。
PSPNetを弱いコンピューティングリソースするのはなかなか至難の業です。

本来、マルチGPU環境で行われるレベルですので。

[1] input_sizeや、PyramidPoolingを変えると、他とのバランスやアノテーションデータとの整合性に気をつける必要があります

[2] 転移学習からスクラッチに変えたとのことですが、本書の通りでもスクラッチからでは、まったくうまくできません。本来は3GPUで3日ほどかかりますので。
そこで本書では、転移学習にしています。
今回、うまくいかないのは、これが一番の原因と思われます。

スクラッチでやるならPSPNetの論文を詳細に読んで、学習方法などを本書よりも厳密に実施する必要があります（学習率の変化など）。

[3] GPUのメモリサイズが小さいなかで、本書の通りに進める解決策としては、
p. 171あたりに書いていますが、multiple minibatchの、batch_multiplier=3の部分を大きくします。
本書では、batch_size = 8でDataLoaderを作成し、batch_multiplier=3として、
24個分の損失を利用して、パラメータを更新しています。

小さいメモリで動作するように、例えば、batch_size = 3、batch_multiplier=8にすると、1回のバッチサイズが小さいので、小さなメモリでも、乗るかもしれません。


この解決策でうまくいくかは分からないのですが、
今回の条件でどうにかするとしたら、まずこれを私なら試してみます。

どうぞよろしくお願い致します。

**Comment by otsuka0212** [comment]
コメント、ありがとうございます。返信文章作成中のため、また、夜に送信します。

**Comment by otsuka0212** [comment]
改めて、回答ありがとうございました。

> [1] input_sizeや、PyramidPoolingを変えると、他とのバランスやアノテーションデータとの整合性に気をつける必要があります

了解です。
input_sizeに合わせて、チャンネル数や層数を下げてもよいでしょうが、後回しにしています。


> [2] 転移学習からスクラッチに変えたとのことですが、本書の通りでもスクラッチからでは、まったくうまくできません。本来は3GPUで3日ほどかかりますので。
そこで本書では、転移学習にしています。
今回、うまくいかないのは、これが一番の原因と思われます。

了解です。
epoch数とlrを上げてみます。ただし、batch_sizeを下げるので、lrはそれも考慮しておきます。

> 小さいメモリで動作するように、例えば、batch_size = 3、batch_multiplier=8にすると、1回のバッチサイズが小さいので、小さなメモリでも、乗るかもしれません。

記載忘れましたが、batch_multiplierは対策してあります。デフォルトの24が保持されるようにしています。それだけではダメでした。



特定クラスに特化することを考えていて、幾つか方法を考えています。試行するか未定です。
①クラス数を減らす。
　train_model関数で、anno_class_imgesの値を特定クラスのみにフィルタリングする。
②特定のクラスが写っている画像のみ学習・評価。
　dataのSegmentationフォルダとMainフォルダのtxtでandを取り、特定のクラスのセグメンテーション画像リストを作成、make_datapath_listで読みだす。



また、進捗しましたら、連絡します。

**Comment by YutaroOgawa** [comment]
@otsuka0212 さま

早速のご返信ありがとうございます。

また、多くの読者の皆さまにも役立つ、
詳細な回答もいただき、ありがとうございます。

根本的に、PSPNetを小さなメモリサイズのGPUで実施すること自体が大変難しいことです。
そのため、これ以上の力になるコメントを返すことができず、大変申し訳ございません。

もし進捗が出ましたら、またコメントいただければ幸いです。
ありがとうございます。

**Comment by otsuka0212** [comment]
PyTorch版のセグメンテーションを試行したいだけだったのですが、
PSPNetはdilated conv等リッチなNetなので、
プアなGPUPCには不適だったと思いますが、
何か分かったら、情報出しいたします。
（深追いはしないと思います。）

**Comment by otsuka0212** [comment]
シンプルに解決しました。
[2]でご指摘いただいた通り、転移学習に戻しました。
プアなGPUでも学習させるために、軽量化してスクラッチ学習するのではなく、pspnet50_ADE20K.pthを転移後に最終層だけ学習するようにしました。（ハイパーパラメータは記載の値に戻しました。）。
同等の性能を確認しました。

```
# パラメータロード後に、パラメータを固定
for param in net.parameters():
    param.requires_grad = False
```

```
# 最終層のみ学習
base_lr = 1e-2
optimizer = optim.SGD([
    {'params': net.decode_feature.classification.parameters(), 'lr': base_lr},
    {'params': net.aux.classification.parameters(), 'lr': base_lr},
], momentum=0.9, weight_decay=0.0001)
```

オリジナル
![オリジナル](https://user-images.githubusercontent.com/43694878/80927454-f9b40b80-8dd8-11ea-9647-147fc8dd9078.PNG)

最終層のみ学習
![最終層のみ](https://user-images.githubusercontent.com/43694878/80927459-05073700-8dd9-11ea-8be4-46c52ed8b05e.PNG)

最初に軽量化→スクラッチにいってしまって、お手数をお掛けしました。

**Comment by YutaroOgawa** [comment]
@otsuka0212 さま

ご連絡ありがとうございます。
いえいえ、本書から、いろいろなチャレンジをしてくださって、
著者冥利に尽きます。

とても嬉しいです！
ありがとうございます
