### ISSUE TITLE
【質問】【3章：p.168】pspnet50_ADE20k.pthの読み込みについて

### ISSUE THREAD

**Issue by kmtYNG** [YutaroOgawa/pytorch_advanced#73]
本書p.168に書かれているコードの実行に対して以下のエラーが吐かれました。
Error(s) in loading state_dict for PSPNet:
	Missing key(s) in state_dict: "feature_res_1.block1.cbr_3.conv.weight", .....

PSPNetについて、gitに挙げていただいているものをそのまま利用しています。
どのように対処、またはどのような点を確認すれば良いか教えていただけると幸いです。

**Comment by YutaroOgawa** [comment]
@kmtYNG さま

1カ月ほど前にAWSにて構築した環境で、さきほど動作を確認を実施しましたが、
該当部分は問題なく動作しました。

pspnet50_ADE20K.pth
をダウンロードしてきて、weightフォルダに配置し、実行しています。

pspnet50_ADE20K.pth
のダウンロードに失敗している、ダウンロード途中にファイルが破損してしまっている
可能性があるかもしれません（他に原因が思い浮かばず）。

3_semantic_segmentation/make_folders_and_data_downloads.ipynb
に記載の手続きで、
pspnet50_ADE20K.pth
を再度ダウンロードして、配置していただけますでしょうか？

**Comment by kmtYNG** [comment]
祝日中のご返信ありがとうございます。
再ダウンロードしてみます。

**Comment by YutaroOgawa** [comment]
@kmtYNG さま

ありがとうございます。どうぞ宜しくお願い致します。
