### ISSUE TITLE
第4章　4-2_DataLoader.ipynbの訓練データの正解情報として使うアノテーションデータの作成のエラー

### ISSUE THREAD

**Issue by kato76** [YutaroOgawa/pytorch_advanced#75]
第4章　4-2_DataLoader.ipynbの訓練データの正解情報として使うアノテーションデータの作成の中の左ひじのHeatmapの作成　以降でエラーが出るのですが、原因わかりますでしょうか。
（コード）
# 左肘のheatmapを確認

# 元画像
img = Image.fromarray(np.uint8(img*255))
img = np.asarray(img.convert('RGB'))

# 左肘
heat_map = heatmaps[:, :, 6]  # 6は左肘
heat_map = Image.fromarray(np.uint8(cm.jet(heat_map)*255))
heat_map = np.asarray(heat_map.convert('RGB'))
heat_map = cv2.resize(
    heat_map, (img.shape[1], img.shape[0]), interpolation=cv2.INTER_CUBIC)
# 注意：heatmapは画像サイズが1/8になっているので拡大する

# 合成して表示
blend_img = cv2.addWeighted(img, 0.5, heat_map, 0.5, 0)
plt.imshow(blend_img)
plt.show()

（エラー）
-------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-66712b596db0> in <module>()
      4 # 左肘
      5 heat_map = heatmaps[:, :, 6]  # 6は左肘
----> 6 heat_map = Image.fromarray(np.uint8(cm.jet(heat_map)*255))
      7 heat_map = np.asarray(heat_map.convert('RGB'))
      8 heat_map = cv2.resize(

2 frames
<__array_function__ internals> in any(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     86                 return reduction(axis=axis, dtype=dtype, out=out, **passkwargs)
     87             else:
---> 88                 return reduction(axis=axis, out=out, **passkwargs)
     89 
     90     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

TypeError: any() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:
 * ()
 * (name dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis
 * (int dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis

**Comment by YutaroOgawa** [comment]
@kato76 さま

ご連絡ありがとうございます。

思いつく可能性は2点あります。

1つ目は、第4章のデータは大きくて、ダウンロードと解凍時にファイルの欠損が生じる場合があります。

closedしていたissueですが、その現象かこちら2点です。

https://github.com/YutaroOgawa/pytorch_advanced/issues/66

https://github.com/YutaroOgawa/pytorch_advanced/issues/63

2つ目は、ここ最近PyTorchがバージョン1.5になり、バージョン1.4では動作していたものが、バージョン1.5で@kato76 さま

ご連絡ありがとうございます。

思いつく可能性は2点あります。

1つ目は、第4章のデータは大きくて、ダウンロードと解凍時にファイルの欠損が生じる場合があります。ファイルが存在してるか確認をお願いいたします。

closedしていたissueですが、その現象かこちら2点です。

https://github.com/YutaroOgawa/pytorch_advanced/issues/66

https://github.com/YutaroOgawa/pytorch_advanced/issues/63

2つ目は、ここ最近PyTorchがバージョン1.5になり、バージョン1.4では動作していたものが、バージョン1.5でエラーになる可能性があります。

その点と解決例（バージョンダウン）はこちらになります。

https://github.com/YutaroOgawa/pytorch_advanced/issues/71

（あと、Matplotライブラリのバージョンが最近アップしたことも、懸念ではあります）

お手数をおかけします。まずはこのあたりに問題がないか、ご確認のほどをお願い致します。

**Comment by kato76** [comment]
ありがとうございます。＃66のように、再度、マスクデータをダウンロードして解凍して、直りました。make_folders_and_data_downloads

やはり、マスクデータの中にmask_COCO_val2014_000000000488.jpgが、なかったようです。

**Comment by kato76** [comment]
↓たぶん、こういうことだったんですね。ありがとうございます。
「COCO.jsonに記載はあるがmask.tar.gzには含まれていないマスク画像がありエラーが発生している．mask_COCO_val2014_000000000488.jpg以外にも存在しない画像が複数枚ある．」

**Comment by YutaroOgawa** [comment]
@kato76 さま

早速のご対応ならびに、ご報告をありがとうございます。
他の読者の皆さまにも役立ちます。

誠にありがとうございます。
