### ISSUE TITLE
第2章 p90 class DBoxの実装について

### ISSUE THREAD

**Issue by HiroshiMiyashita** [YutaroOgawa/pytorch_advanced#76]
# アスペクト比1の大きいDBox [cx,cy, width, height]
                # 'max_sizes': [60, 111, 162, 213, 264, 315],
                s_k_prime = sqrt(s_k * (self.max_sizes[k]/self.image_size))
                mean += [cx, cy, s_k_prime, s_k_prime]

となっておりますが、

                # アスペクト比1の大きいDBox [cx,cy, width, height]
                # 'max_sizes': [60, 111, 162, 213, 264, 315],
                s_k_prime = self.max_sizes[k]/self.image_size
                mean += [cx, cy, s_k_prime, s_k_prime]

の間違いではないでしょうか。
s_k_primeを計算する際にs_kの値を使う理由や、sqrt()でルートを取る理由はないように考えられます。

**Comment by YutaroOgawa** [comment]
@HiroshiMiyashita さま

ありがとうございます。
なるほど、気づきませんでした。
鋭い視点をありがとうございます。

第2章の該当部分などについては、学習済みモデルを流用できるように、
書面記載の通り、以下を参考に作っております。

https://github.com/amdegroot/ssd.pytorch/blob/8dd38657a3b1df98df26cf18be9671647905c2a0/layers/functions/prior_box.py

こちらの実装でのアスペクト比という言葉に合わしているのですが、
一般にアスペクト比といういうと、長さの比率をイメージします。

ですが、参考にしている実装は”面積比率をアスペクト比と呼んでいる”（と思われる）ため、
ルートを計算している（と思われます）。

ここまで細かく丁寧に確認、いただき、ありがとうございます。

**Comment by HiroshiMiyashita** [comment]
学習済みモデルを使用したいために、実装を合わせたとのこと理解しました。

ただ、
s_k_primeの値は、 s_k の sqrt(self.max_sizes[k] / self.min_sizes[k]) 倍の値となるため、
コード内のself.max_sizesの以下のコメントは間違っていることになります。

self.max_sizes = cfg['max_sizes']  # [60, 111, …] 大きい正方形のDBoxのピクセルサイズ

この部分について修正もしくは、何らかの追記が必要ではないでしょうか。

**Comment by YutaroOgawa** [comment]
@HiroshiMiyashita さま

ありがとうございます。
こちらに、正確には面積と、コメントを追記いたしました。
また、誤植ラベルを貼り付けさせていただきました。

細かな点まで、ご確認いただき、誠にありがとうございます。
今後ともどうぞ宜しくお願い致します。
