### ISSUE TITLE
【質問】第2章　2-8_SSD_inference.ipynbにて　

### ISSUE THREAD

**Issue by kato76** [YutaroOgawa/pytorch_advanced#83]
いつも丁寧に教えてくださり本当にありがとうございます。

SSDの推論2-8_SSD_inference.ipynbで、検出された物体のバウンディングボックスの座標と、
物体のラベル名、信頼度を　テキストとして出力したい場合、どのようにすればよろしいでしょうか。
いろいろ試しましたがうまくいきませんでした。可能でしたらご教授いただきたく、よろしくお願い致します。

**Comment by YutaroOgawa** [comment]
@kato76 さま

返事が遅くなり、申し訳ございません。
ご質問ありがとうございます。

2-8_SSD_inference.ipynbでは
ssd = SSDPredictShow(eval_categories=voc_classes, net=net)
で、バウンディングボックスの座標や、物体名などを取得しています。

SSDPredictShowは、フォルダ「utils」の/ssd_predict_show.py

https://github.com/YutaroOgawa/pytorch_advanced/blob/master/2_objectdetection/utils/ssd_predict_show.py

で定義しています。

このファイルの関数vis_bboxが、描画をする関数です。

ここに与えている引数の、bbox, , scores, label_namesがそれぞれ、
バウンディングボックスの座標、確信度、物体のラベル名です。

これは、関数ssd_predictを実行すると取得できます。

こちらのファイルを見て、このクラスSSDPredictShowを自由に書き換えていただければと思います。

どうぞよろしくお願い致します。

**Comment by kato76** [comment]
了解しました。ありがとうございます。
