### ISSUE TITLE
【第9章】Kinetics動画をダウンロードしたい

### ISSUE THREAD

**Issue by take0212** [YutaroOgawa/pytorch_advanced#91]
第9章のKinetics動画をダウンロードできず、困っています。
何かアドバイスありましたら、よろしくお願いいたします。

OSはWindowsで、仮想環境はAnacondaで作成しています。

「9-4_1_kinetics_download_for_python2.ipynb」の記載に沿い、
Python2系の仮想環境を、environment.ymlを指定して、作成使用しましたが、エラーが発生しました。

そこで、Python2系の仮想環境をマニュアルで作成し、
各モジュールをマニュアルでインストールしました。

それから、「9-4_1_kinetics_download_for_python2.ipynb」を実行すると、
kinetics_videosフォルダやtmpフォルダが自動生成され、tmpフォルダにはファイルがダウンロードされるのですが、
ipynbファイルは「＊」から変わらず、tmpフォルダもそのままになってしまいます。

以下のいずれかをアドバイスいただけないでしょうか。
①windowsで実行可能なenvironment.ymlを提供いただく。
②スクリプトを使わず、マニュアルでダウンロードする方法（URL、保存先）を教えていただく。

よろしくお願いいたします。

**Comment by YutaroOgawa** [comment]
@take0212 さま

大変申し訳ございません。
p. 454の9章第2節の冒頭に、

>　本節ではECOの2D NetモジュールであるInception-v2の実装を行います。本章の実装は
GitHub：zhang-can/ECO-pytorch［ 4］ を参考にしています。なお本章のプログラムはすべて
Ubuntuでの動作を前提としています。

と記載しており、本書の第9章はUbuntuでの動作を前提としております。

動画をダウンロードしてもさらにその先もおそらく動かない部分が出てきます。

これは、動画や画像をいじる系の各種ライブラリが、pipより低層のapt-getなど、OSレベルまで動作の依存範囲が広がっているからです。

手元のWindowsマシンで実施したい気持ちも大変分かるのですが、本章をUbuntuやMac以外での実施は難しく、どうにか宜しくお願いいたします。

**Comment by take0212** [comment]
問題を以下のように回避しました。

①Kinetics動画データのダウンロード（9-4_1_kinetics_download_for_python2.ipynb）と、画像データへの分割（9-4_2_convert_mp4_to_jpeg.ipynb）は、google colab上で実行し、作成されたファイルをwindowsにコピーしました。
youtube-dlをpipインストールするだけで、正常に動作しました。
!python2は!python2のままです。
ドライブのマウントはご自身の環境に合わせてお願いします。

②VideoDatasetのpull_itemメソッドに区切り文字があるので、修正必要です。2つ目だけ修正します。
label = (dir_path.split('/')[3].split('\\')[0])
9-4_3_ECO_DataLoader.ipynbとutils\kinetics400_eco_dataloader.pyの両方です。

③ffmpegをインストールすることで、画像データへの分割（9-4_2_convert_mp4_to_jpeg.ipynb）がwindowsでも実行可能かは未確認です。

ご参考まで。

**Comment by YutaroOgawa** [comment]
@take0212 さま

他の多くの読者のみなさまにとって、大変有益な情報をありがとうございます。
本当は私がそこまで手が回れば良いのですが、申し訳ございません。
とても助かります。

誠にありがとうございます！！

**Comment by take0212** [comment]
お役に立てて光栄です。

「9-4_1_kinetics_download_for_python2.ipynb」のWindowsでのPython2の仮想環境構築も何か間違えた可能性があります。
興味ある方がおりましたら、調査いただければ。
