### ISSUE TITLE
1-3 転移学習の実装について

### ISSUE THREAD

**Issue by tiger1997s** [YutaroOgawa/pytorch_advanced#93]

**Comment by YutaroOgawa** [comment]
@tiger1997s さま

ご返信が遅くなってしまい、大変申し訳ございません。
（今週、平日対応が難しく）

closeされ、自己解決できたとのことで宜しいでしょうか？
もし、お困りの点などございましたら、また気軽にご連絡くださいませ。

レスポンスが2日間できず、遅くなってしまい、大変申し訳ございません。
